#!/bin/sh

VERBOSITY=0
VERBOSITYFLAGS=""
while test "$1" = "-v"; do
	VERBOSITY=$((VERBOSITY+1))
	VERBOSITYFLAGS="$VERBOSITYFLAGS -v"
	shift
done

run()
{
	if test $VERBOSITY -gt 1; then echo "$@"; fi
	"$@" || exit 1
}

GPPTARGET=`grep -n gpp *.go? 2>/dev/null | cut -d ':' -f 1 | uniq | grep -v gpp`
test "$GPPTARGET" != "" && run gpp -r

DIRS="bits log mem"
BASE=`pwd`
for dir in `echo $DIRS`; do
	run cd $dir && run go run cmd/generate.go && cd $BASE
done
