/* File generated by 'cmd/generate.go'; DO NOT EDIT! */
package log

import "unsafe"

func (f *Formatter) D(d int) *Formatter {
	if f != nil {
		f.Fmt.D(d)
	}
	return f
}

func (f *Formatter) D32(d int32) *Formatter {
	if f != nil {
		f.Fmt.D32(d)
	}
	return f
}

func (f *Formatter) D64(d int64) *Formatter {
	if f != nil {
		f.Fmt.D64(d)
	}
	return f
}

func (f *Formatter) Date(t int64) *Formatter {
	if f != nil {
		f.Fmt.Date(t)
	}
	return f
}

func (f *Formatter) DateTime(t int64) *Formatter {
	if f != nil {
		f.Fmt.DateTime(t)
	}
	return f
}

func (f *Formatter) Err(err error) *Formatter {
	if f != nil {
		f.Fmt.Err(err)
	}
	return f
}

func (f *Formatter) E(e float64) *Formatter {
	if f != nil {
		f.Fmt.E(e)
	}
	return f
}

func (f *Formatter) E32(e float32) *Formatter {
	if f != nil {
		f.Fmt.E32(e)
	}
	return f
}

func (f *Formatter) E64(e float64) *Formatter {
	if f != nil {
		f.Fmt.E64(e)
	}
	return f
}

func (f *Formatter) F(f_ float64) *Formatter {
	if f != nil {
		f.Fmt.F(f_)
	}
	return f
}

func (f *Formatter) F32(f_ float32) *Formatter {
	if f != nil {
		f.Fmt.F32(f_)
	}
	return f
}

func (f *Formatter) F64(f_ float64) *Formatter {
	if f != nil {
		f.Fmt.F64(f_)
	}
	return f
}

func (f *Formatter) G(g float64) *Formatter {
	if f != nil {
		f.Fmt.G(g)
	}
	return f
}

func (f *Formatter) G32(g float32) *Formatter {
	if f != nil {
		f.Fmt.G32(g)
	}
	return f
}

func (f *Formatter) G64(g float64) *Formatter {
	if f != nil {
		f.Fmt.G64(g)
	}
	return f
}

func (f *Formatter) I(i int) *Formatter {
	if f != nil {
		f.Fmt.I(i)
	}
	return f
}

func (f *Formatter) I32(i int32) *Formatter {
	if f != nil {
		f.Fmt.I32(i)
	}
	return f
}

func (f *Formatter) I64(i int64) *Formatter {
	if f != nil {
		f.Fmt.I64(i)
	}
	return f
}

func (f *Formatter) P(p unsafe.Pointer) *Formatter {
	if f != nil {
		f.Fmt.P(p)
	}
	return f
}

func (f *Formatter) Q(q string) *Formatter {
	if f != nil {
		f.Fmt.Q(q)
	}
	return f
}

func (f *Formatter) S(s string) *Formatter {
	if f != nil {
		f.Fmt.S(s)
	}
	return f
}

func (f *Formatter) W(width int) *Formatter {
	if f != nil {
		f.Fmt.W(width)
	}
	return f
}

func (f *Formatter) Prec(prec int) *Formatter {
	if f != nil {
		f.Fmt.Prec(prec)
	}
	return f
}
