package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
)

func String(w *bufio.Writer, s string) {
	w.WriteString(s)
	w.WriteRune('\n')
}

func main() {
	types := [...]string{"byte", "int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64", "int", "uint", "float32", "float64", "complex64", "complex128"}

	const path = "arena_helpers.go"
	f, err := os.Create(path)
	if err != nil {
		log.Fatalf("Failed to create %q: %v", path, err)
	}
	b := bufio.NewWriter(f)

	String(b, "/* File generated by 'cmd/generate.go'; DO NOT EDIT! */")
	String(b, "package mem\n")
	String(b, `import (
	"unsafe"

	"github.com/anton2920/gofa/go/types"
)`)
	for _, typ := range types {
		String(b, fmt.Sprintf(`
func (a *Arena) Push%s() *%s {
	return (*%s)(a.PushSizeWithAlignment(unsafe.Sizeof(%s(0)), unsafe.Alignof(%s(0))))
}`, strings.Title(typ), typ, typ, typ, typ))
		String(b, fmt.Sprintf(`
func (a *Arena) Push%sArray(n int) []%s {
	ptr := a.PushSizeWithAlignment(unsafe.Sizeof(%s(0))*uintptr(n), unsafe.Alignof(%s(0)))
	return *(*[]%s)(unsafe.Pointer(&types.SliceHeader{Data: uintptr(ptr), Len: n, Cap: n}))
}`, strings.Title(typ), typ, typ, typ, typ))
		String(b, fmt.Sprintf(`
func (a *Arena) Push%sArrayFrom(arr []%s) []%s {
	if a.AllocationComesFromHere(unsafe.Pointer(&arr[0]), uintptr(len(arr))*unsafe.Sizeof(arr[0])) {
		return arr
	}
	narr := a.Push%sArray(len(arr))
	copy(narr, arr)
	return narr
}`, strings.Title(typ), typ, typ, strings.Title(typ)))
		String(b, fmt.Sprintf(`
func (a *Arena) Repush%sArray(old []%s, n int) []%s {
	ptr := a.RepushSizeWithAlignment(unsafe.Pointer(&old[0]), unsafe.Sizeof(%s(0))*uintptr(len(old)), unsafe.Sizeof(%s(0))*uintptr(n), unsafe.Alignof(%s(0)))
	return *(*[]%s)(unsafe.Pointer(&types.SliceHeader{Data: uintptr(ptr), Len: n, Cap: n}))
}`, strings.Title(typ), typ, typ, typ, typ, typ, typ))
	}

	if err := b.Flush(); err != nil {
		log.Fatalf("Failed to flush generated file to disk: %v", err)
	}
}
