package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
)

func String(w *bufio.Writer, s string) {
	w.WriteString(s)
	w.WriteRune('\n')
}

func main() {
	types := [...]string{"uint8", "uint16", "uint32", "uint64", "uint"}

	const path = "flags.go"
	f, err := os.Create(path)
	if err != nil {
		log.Fatalf("Failed to create %s: %v", path, err)
	}
	b := bufio.NewWriter(f)

	String(b, "/* File generated by 'cmd/generate.go'; DO NOT EDIT! */")
	String(b, "package bits\n")
	for _, typ := range types {
		n := typ[len("uint"):]
		fmt.Fprintf(b, `type Flags%s %s

func (f *Flags%s) Del(g Flags%s) {
	*f = (*f) & (^g)
}

func (f Flags%s) Has(g Flags%s) bool {
	return (f & g) == g
}

func (f Flags%s) Have(g Flags%s) bool {
	return f.Has(g)
}

func (f *Flags%s) Set(g Flags%s) {
	*f = (*f) | g
}

func (f *Flags%s) Toggle(g Flags%s) {
	*f = (*f) ^ g
}
`, n, typ, n, n, n, n, n, n, n, n, n, n)
	}

	if err := b.Flush(); err != nil {
		log.Fatalf("Failed to flush generated file to disk: %v", err)
	}
}
