/* File generated by 'cmd/generate.go'; DO NOT EDIT! */
package bits

type Flags8 uint8

func (f *Flags8) Del(g Flags8) {
	*f = (*f) & (^g)
}

func (f Flags8) Has(g Flags8) bool {
	return (f & g) == g
}

func (f Flags8) Have(g Flags8) bool {
	return f.Has(g)
}

func (f *Flags8) Set(g Flags8) {
	*f = (*f) | g
}

func (f *Flags8) Toggle(g Flags8) {
	*f = (*f) ^ g
}

type Flags16 uint16

func (f *Flags16) Del(g Flags16) {
	*f = (*f) & (^g)
}

func (f Flags16) Has(g Flags16) bool {
	return (f & g) == g
}

func (f Flags16) Have(g Flags16) bool {
	return f.Has(g)
}

func (f *Flags16) Set(g Flags16) {
	*f = (*f) | g
}

func (f *Flags16) Toggle(g Flags16) {
	*f = (*f) ^ g
}

type Flags32 uint32

func (f *Flags32) Del(g Flags32) {
	*f = (*f) & (^g)
}

func (f Flags32) Has(g Flags32) bool {
	return (f & g) == g
}

func (f Flags32) Have(g Flags32) bool {
	return f.Has(g)
}

func (f *Flags32) Set(g Flags32) {
	*f = (*f) | g
}

func (f *Flags32) Toggle(g Flags32) {
	*f = (*f) ^ g
}

type Flags64 uint64

func (f *Flags64) Del(g Flags64) {
	*f = (*f) & (^g)
}

func (f Flags64) Has(g Flags64) bool {
	return (f & g) == g
}

func (f Flags64) Have(g Flags64) bool {
	return f.Has(g)
}

func (f *Flags64) Set(g Flags64) {
	*f = (*f) | g
}

func (f *Flags64) Toggle(g Flags64) {
	*f = (*f) ^ g
}

type Flags uint

func (f *Flags) Del(g Flags) {
	*f = (*f) & (^g)
}

func (f Flags) Has(g Flags) bool {
	return (f & g) == g
}

func (f Flags) Have(g Flags) bool {
	return f.Has(g)
}

func (f *Flags) Set(g Flags) {
	*f = (*f) | g
}

func (f *Flags) Toggle(g Flags) {
	*f = (*f) ^ g
}
