package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"unicode"

	"github.com/anton2920/gofa/strings"
)

func String(w *bufio.Writer, s string) {
	w.WriteString(s)
	w.WriteRune('\n')
}

func StringSliceContains(xs []string, x string) bool {
	for i := 0; i < len(xs); i++ {
		if xs[i] == x {
			return true
		}
	}
	return false
}

func ProcessFile(b *bufio.Writer, path string) error {
	blacklist := [...]string{"InitWithUnsafePointer", "InitWithBytePointer", "InitWithByteSlice", "String", "Reset"}

	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to open source file %q: %v", path, err)
	}
	defer f.Close()

	rd := bufio.NewReader(f)
	for {
		line, err := rd.ReadString('\n')
		if err != nil {
			break
		}

		const prefix = "func (f *Formatter) "
		if strings.StartsWith(line, prefix) {
			line = line[len(prefix):]
			lparen := strings.FindChar(line, '(')
			if lparen > 0 {
				fn := line[:lparen]
				if (unicode.IsUpper(rune(fn[0]))) && (!StringSliceContains(blacklist[:], fn)) {
					rparen := strings.FindChar(line, ')')
					if rparen > 0 {
						params := line[lparen+1 : rparen]
						sp := strings.FindChar(params, ' ')
						if sp > 0 {
							name := params[:sp]
							fmt.Fprintf(b, `
func (f *Formatter) %s(%s) *Formatter {
	if f != nil {
		f.Fmt.%s(%s)
	}
	return f
}
`, fn, params, fn, name)
						}
					}
				}
			}
		}
	}

	return nil
}

func main() {
	const path = "formatter_helpers.go"
	f, err := os.Create(path)
	if err != nil {
		log.Fatalf("Failed to create %q: %v", path, err)
	}
	b := bufio.NewWriter(f)

	String(b, "/* File generated by 'cmd/generate.go'; DO NOT EDIT! */")
	String(b, "package log\n")
	String(b, `import "unsafe"`)

	ProcessFile(b, "../fmt/formatter.go")
	ProcessFile(b, "../fmt/formatter_std.go")

	if err := b.Flush(); err != nil {
		log.Fatalf("Failed to flush generated file to disk: %v", err)
	}
}
