package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
	"unicode"
)

func String(w *bufio.Writer, s string) {
	w.WriteString(s)
	w.WriteRune('\n')
}

func StringSliceContains(xs []string, x string) bool {
	for i := 0; i < len(xs); i++ {
		if xs[i] == x {
			return true
		}
	}
	return false
}

func main() {
	blacklist := [...]string{"InitWithUnsafePointer", "InitWithBytePointer", "InitWithByteSlice", "String", "Reset"}

	const path = "formatter_helpers.go"
	f, err := os.Create(path)
	if err != nil {
		log.Fatalf("Failed to create %q: %v", path, err)
	}
	b := bufio.NewWriter(f)

	const srcPath = "../fmt/formatter.go"
	src, err := os.Open(srcPath)
	if err != nil {
		log.Fatalf("Failed to open source file %q: %v", srcPath, err)
	}

	String(b, "/* File generated by 'cmd/generate.go'; DO NOT EDIT! */")
	String(b, "package log\n")
	String(b, `import "unsafe"`)

	scanner := bufio.NewScanner(src)
	for scanner.Scan() {
		line := scanner.Text()

		const prefix = "func (f *Formatter) "
		if strings.HasPrefix(line, prefix) {
			line = line[len(prefix):]
			lparen := strings.IndexByte(line, '(')
			if lparen > 0 {
				fn := line[:lparen]
				if (unicode.IsUpper(rune(fn[0]))) && (!StringSliceContains(blacklist[:], fn)) {
					rparen := strings.IndexByte(line, ')')
					if rparen > 0 {
						params := line[lparen+1 : rparen]
						sp := strings.IndexByte(params, ' ')
						if sp > 0 {
							name := params[:sp]
							fmt.Fprintf(b, `
func (f *Formatter) %s(%s) *Formatter {
	if f != nil {
		f.Fmt.%s(%s)
	}
	return f
}
`, fn, params, fn, name)
						}
					}
				}
			}
		}
	}

	if err := b.Flush(); err != nil {
		log.Fatalf("Failed to flush generated file to disk: %v", err)
	}
}
