/* File generated by "gpp -r -l ./net/html/pagination.go ./generate"; DO NOT EDIT. */

package html

import "github.com/anton2920/gofa/net/url"

func FillPaginationFromValues(vs url.Values, pagination *Pagination) {
	pagination.CurrentPage, _ = vs.GetInt("CurrentPage")
	pagination.ItemsPerPage, _ = vs.GetInt("ItemsPerPage")
	if pagination.ItemsPerPage == 0 {
		pagination.ItemsPerPage = DefaultItemsPerPage
	}
}

func FillPaginationsFromValues(vs url.Values, paginations []Pagination) {
}
